export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const PROFILE_ROUTE = '/profile'
export const REGISTER_ROUTE = '/register'
export const RESET_PASSWORD_ROUTE = '/reset_password'
export const INTERIOR_ROUTE = '/interior'
